# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenName', models.CharField(default=None, max_length=255)),
                ('familyName', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('None', None)], default=None, max_length=6)),
                ('location', models.CharField(default=None, max_length=255)),
                ('timezone', models.CharField(default=None, max_length=255)),
                ('bio', models.CharField(default=None, max_length=255)),
                ('site', models.CharField(default=None, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.User')),
            ],
        ),
    ]
