# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20170627_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupuserinfo',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lookupuserinfo',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lookupuserinfo',
            name='familyName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lookupuserinfo',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='lookupuserinfo',
            name='givenName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lookupuserinfo',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lookupuserinfo',
            name='site',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lookupuserinfo',
            name='timeZone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
